### ISSUE TITLE
Author Javadoc field

### ISSUE THREAD

**Issue by exercitussolus** [ubicity-devs/ubicity-core#2]
I am certain there was an @author field in the Javadoc, as : "@author Jan van Oort". 

Sucks to see that was taken away. Kind of makes the entire idea of open-sourcing ubicity ridiculous. You could have left it, and could have added an "@author <whoever>" tag for yourself.

**Comment by christoph-r** [comment]
Acutally in open source software i do not see why individual ownership should be implied as many other persons are also contributing to these projects.

As many other organizations (Apache, Wordpress ...) including thier projects are going to remove the @author tags we also head in that direction.

Honstely, removing indidual contributions in source actually strengthens the community effect and still, all contributors are listed in GIT history log but also maintains clean code without loosing any revision information.

**Comment by exercitussolus** [comment]
One simple answer: transparency. Having author information makes
development history more transparent, and more traceable.



*Fortuna audaces adiuvat - hos solos ? *
